FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git \
 && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install --no-cache-dir .

ENV OPENAI_BASE_URL=http://localhost:8081/v1

CMD ["cwhy", "--llm", "meta-llama/Llama-3.2-3B-Instruct", "---", "python", "user_input_code.py"]
